title: My Jekyll Site
author: Your Name
description: >- # this means to ignore newlines until "baseurl"
  A simple Jekyll site hosted on GitHub Pages.
baseurl: "" # the subpath of your site, e.g., /blog
url: "https://obsidiandrake.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
